<meta charset="utf-8">
<meta http-equiv="x-ua-compatible" content="ie=edge">
<title>{{title}}</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
{{#meta.description}}<meta name="description" content="{{meta.description}}">{{/meta.description}}
{{#meta.og.locale}}<meta property="og:locale" content="{{meta.og.locale}}">{{/meta.og.locale}}
{{#meta.og.type}}<meta property="og:type" content="{{meta.og.type}}">{{/meta.og.type}}
{{#meta.og.title}}<meta property="og:title" content="{{meta.og.title}}">{{/meta.og.title}}
{{#meta.og.description}}<meta property="og:description" content="{{meta.og.description}}">{{/meta.og.description}}
{{#meta.og.url}}<meta property="og:url" content="{{meta.og.url}}" />{{/meta.og.url}}
{{#meta.og.site_name}}<meta property="og:site_name" content="{{meta.og.site_name}}" />{{/meta.og.site_name}}
{{#meta.og.image}}<meta property="og:image" content="{{meta.og.image}}" />{{/meta.og.image}}
{{#meta.og.secure_image}}<meta property="og:image:secure_url" content="{{meta.og.secure_image}}" />{{/meta.og.secure_image}}
