<form method="post" action="/register">
    <label for="userFullName"> Full Name
        <input id="userFullName" type="text" name="userFullName">
    </label>
    <label for="userEmail"> Email Address
        <input id="userEmail" type="text" name="userEmail">
    </label>
    <label for="userPassword"> Password
        <input id="userPassword" type="password" name="userPassword">
    </label>
    <input type="submit" value="submit">
</form>
