<?php
$loadedConfigs = $this->getLoadedConfigFiles();

echo $this->renderLabel('<strong>LOADED CONFIGS</strong>', '', 'text-decoration: underline; margin-bottom: 25px;');
if ($loadedConfigs) {
    echo $this->renderSeparator(false);
    foreach ($loadedConfigs as $i => $config) {
        echo $this->renderLabel('<strong>Loaded: </strong>' . $config->config);
        echo $this->renderTrace($config->trace);
        echo $this->renderJson($config->fileContent);
        echo $this->renderSeparator(false);
    }
} else {
    echo $this->renderLabel('No Configs Loaded...');
}

echo $this->renderLabel('<strong>APPLICATION CONFIGURATION</strong>', '', 'text-decoration: underline; margin-top: 25px;');
echo $this->renderJson($this->getConfig());
?>
