<?php
    $loadedModules = $this->getLoadedModules();
?>
<?php if ($loadedModules) { ?>
    <?php foreach ($loadedModules as $module) { ?>
        <span class="fs-label"><strong>Loaded: </strong><?php echo $module->module; ?></span>
        <span class="fs-label">
            <?php echo $this->renderTrace($module->trace); ?>
        </span>
        <hr class="fs-hr">
    <?php } ?>
<?php } else { ?>
<span class="fs-label">No Modules Loaded...</span>
<?php } ?>
