<span class="fs-label"><strong>Template: </strong><?php echo $this->getTemplateId(); ?></span>
<span class="fs-label">
    <span class="fs-pre-wrap">wrap</span>
    <pre class="debugger fs-dark"><?php echo htmlspecialchars($this->getTemplate());?></pre>
</span>
<span class="fs-label"><strong>View Model:</strong></span>
<span class="fs-label">
    <span class="fs-pre-wrap">wrap</span>
    <pre class="debugger fs-dark"><?php echo htmlspecialchars(json_encode($this->getModel(), JSON_PRETTY_PRINT));?></pre>
</span>
