{{#viewObj}}
<div class="admin-data-panel">
<div class="title">
<h1>
    {{singularName}} Object
    <a href="{{collectionUrl}}" class="btn admin-btn">Back</a>
    <a href="{{editObjUrl}}" class="btn admin-btn">Edit</a>
    <a href="{{deleteObjUrl}}" class="btn admin-btn">Delete</a>
</h1>
<h5>id: {{id}}</h5>
</div>
<table class="table data-table table-striped">
    <thead>
        <tr>
            {{#tableHeadings}}
            <th>{{.}}</th>
            {{/tableHeadings}}
        </tr>
    </thead>
    <tbody>
        {{#table}}
        <tr>
            {{#.}}
            <td>
                {{{.}}}
            </td>
            {{/.}}
        </tr>
        {{/table}}
    </tbody>
</table>
</div>
{{/viewObj}}