{{#deleteObj}}
<div class="admin-section">
    <h1>Deleting {{singularName}}</h1>
    <p>Are you sure you want to delete object <strong>{{id}}</strong> from collection {{collectionName}}?</p>
    <form class="admin-form" method="post">
        <input type="hidden" name="objectId" value="{{id}}">
        <input type="submit" class="btn admin-btn" value="Delete">
        <a href="{{collectionsUrl}}" class="btn admin-btn">Cancel</a>
    </form>
</div>
{{/deleteObj}}