<?php
return [
    'required' => 'required',
    'equals' => 'equals',
    'different' => 'different',
    'accepted' => 'accepted',
    'numeric' => 'numeric',
    'integer' => 'integer',
    'length' => 'length',
    'min' => 'min',
    'max' => 'max',
    'in' => 'in',
    'notIn' => 'notIn',
    'ip' => 'ip',
    'email' => 'email',
    'url' => 'url',
    'urlActive' => 'urlActive',
    'alpha' => 'alpha',
    'alphaNum' => 'alphaNum',
    'slug' => 'slug',
    'regex' => 'regex',
    'date' => 'date',
    'dateFormat' => 'dateFormat',
    'dateBefore' => 'dateBefore',
    'dateAfter' => 'dateAfter',
    'contains' => 'contains',
    'boolean' => 'boolean',
    'lengthBetween' => 'lengthBetween',
    'creditCard' => 'creditCard',
    'lengthMin' => 'lengthMin',
    'lengthMin' => 'lengthMin',
    'instanceOf' => 'instanceOf'
];
