<div class="fs-section fs-constants closed">
    <h3 class="fs-title">Injector<span class="fs-openCloseBtn"></span></h3>
    <div class="fs-content">
        <table>
            <tbody>
                <tr>
                    <th>Name</th>
                    <th>Value</th>
                </tr>
                <?php foreach ($this->injectorDebug as $name => $value) { ?>
                <tr>
                    <td style="vertical-align: top;"><?php echo $name; ?></td>
                    <td>
                        <?php
                            if (is_object($value)) echo 'Object "' . get_class($value) . '"';
                            else if (is_array($value)) echo 'Array';
                            else if (is_bool($value) && $value) echo 'true';
                            else if (is_bool($value) && !$value) echo 'false';
                            else if (is_null($value)) echo 'NULL';
                        ?>
                    </td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </div>
</div>
