<!doctype html>
<html class="no-js" lang="">
    <head>
        {{>fire.studio.partial.html.head}}
        {{{inlineStyles}}}
    </head>
    <body>
        <div class="admin-wrapper">
            <header id="admin-header">
                <a href="{{adminHomeUrl}}" class="logo">
                    <span class="inner">{{{logo}}}</span>
                </a>
                <nav class="navbar">

                </nav>
            </header>
            <aside id="admin-sidebar">
                <div class="sidebar-nav">
                    {{#adminMenu}}
                    <ul class="sidebar-nav-menu">
                        {{#.}}
                        <li class="nav-item{{#active}} active{{/active}}">
                            <a href="{{url}}">{{title}}</a>
                        </li>
                        {{/.}}
                    </ul>
                    {{/adminMenu}}
                </div>
            </aside>
            <div id="admin-main">
                <div class="admin-main-inner">
                    <section class="content">
                        {{>fire.studio.admin.page}}
                    </section>
                    {{{debugPanel}}}
                </div>
            </div>
            <footer id="admin-footer">
                <span class="footer-text">{{{footerText}}}</span>
            </footer>
        </div>
        {{{inlineScripts}}}
    </body>
</html>
