{{#adminDataPanel}}
<div class="admin-data-panel">
    <h1 class="title">Manage {{pluralName}}
        <span class="btn new-btn">New {{singularName}}</span>
    </h1>
    {{#searchAvailable}}
    <form class="row search-form">
        <div class="col-12 col-md-8"></div>
        <div class="input-group col-12 col-md-4">
            <input type="text" class="form-control" name="s">
            <div class="input-group-append">
                <input class="btn fs-btn" type="submit" value="Search">
            </div>
        </div>
    </form>
    {{/searchAvailable}}
    <div class="row filters">
        <div class="col-12 col-md-10 col-lg-8 filter-options"></div>
        <div class="col-12 col-md-2 col-lg-4">
            {{#pageNav}}
            <nav class="page-nav">
                <ul class="pagination">
                    <li class="page-item page-prev">
                        {{#previousPage}}<a class="page-link" href="?page={{previousPage}}">&#139;</a>{{/previousPage}}
                        {{^previousPage}}<div class="page-link">&#139;</div>{{/previousPage}}
                    </li>
                    <li class="page-item">
                        <form method="get">
                            <input type="text" class="form-control page-num" value="{{currentPage}}" name="page">
                        </form>
                    </li>
                    <li class="page-item of-num">of {{pageCount}}</li>
                    <li class="page-item page-next">
                        {{#nextPage}}<a class="page-link" href="?page={{nextPage}}">&#155;</a>{{/nextPage}}
                        {{^nextPage}}<div class="page-link">&#155;</div>{{/nextPage}}
                    </li>
                </ul>
            </nav>
            {{/pageNav}}
            {{#hasTableData}}
            <span class="item-count">{{totalCount}} {{singularName}}</span>
            {{/hasTableData}}
        </div>
    </div>
    {{#hasTableData}}
    <table class="table data-table table-striped">
        <thead>
            <tr>
                {{#tableHeadings}}
                <th>{{.}}</th>
                {{/tableHeadings}}
            </tr>
        </thead>
        <tbody>
            {{#table}}
            <tr>
                {{#.}}
                <td>
                    {{value}}
                    {{#hasActionLinks}}
                    <span class="action-links">
                        {{#actionLinks}}
                        {{#.}}<a href="#">{{label}}</a> |{{/.}}
                        {{/actionLinks}}
                    </span>
                    {{/hasActionLinks}}
                </td>
                {{/.}}
            </tr>
            {{/table}}
        </tbody>
    </table>
    {{/hasTableData}}
    {{^hasTableData}}
    <p>No objects found...</p>
    {{/hasTableData}}
</div>
{{/adminDataPanel}}